/**
 * SpecKit Integration Module for Claude-Flow - Phase 1: Foundation Layer
 *
 * This module provides integration between spec-kit's Specification-Driven Development (SDD)
 * workflow and Claude-Flow's memory and agent coordination systems.
 *
 * Phase 1 Components:
 * - SpecKitMemoryBridge: Parses markdown artifacts and stores them in SQLite
 * - SpecVersionTracker: Tracks specification versions and detects cascade changes
 * - Database Schema: SQLite schema for specifications, plans, tasks, and lineage
 *
 * Usage:
 * ```typescript
 * import { SpecKitMemoryBridge, SpecVersionTracker, createSpecKitIntegration } from './integrations/speckit';
 *
 * const integration = await createSpecKitIntegration({
 *   dbPath: './.speckit/speckit.db',
 *   specsDirectory: './specs',
 * }, logger);
 *
 * // When spec is generated by /speckit.specify
 * const { specId } = await integration.bridge.onSpecGenerated(
 *   './specs/001-feature/spec.md',
 *   'spec-agent'
 * );
 *
 * // When plan is generated by /speckit.plan
 * const { planId } = await integration.bridge.onPlanGenerated(
 *   './specs/001-feature/plan.md',
 *   specId,
 *   'plan-agent',
 *   {
 *     researchPath: './specs/001-feature/research.md',
 *     dataModelPath: './specs/001-feature/data-model.md',
 *     contractsDir: './specs/001-feature/contracts',
 *     quickstartPath: './specs/001-feature/quickstart.md',
 *   }
 * );
 *
 * // When tasks are generated by /speckit.tasks
 * const { taskIds } = await integration.bridge.onTasksGenerated(
 *   './specs/001-feature/tasks.md',
 *   planId,
 *   'task-agent'
 * );
 *
 * // Track version changes and detect cascade
 * const cascadeResult = await integration.versionTracker.detectCascade(specId);
 * ```
 *
 * @module integrations/speckit
 */

import type { ILogger } from '../../core/logger.js';
import {
  SpecKitMemoryBridge,
  type SpecKitConfig,
  type ParsedSpecification,
  type ParsedPlan,
  type ParsedTask,
  type ParsedUserStory,
  type ArtifactLineageEntry,
} from './memory-bridge.js';
import {
  SpecVersionTracker,
  type VersionInfo,
  type VersionDiff,
  type CascadeResult,
  type SpecSnapshot,
} from './version-tracker.js';

// Phase 6: Team Process & Integration Layer
import { StatusDashboard, type DashboardConfig } from './dashboard/status-dashboard.js';
import { AuditTrail, type AuditConfig } from './audit/audit-trail.js';
import { ProcessGates, type GatesConfig } from './process/gates.js';
import { WorkflowEngine, type WorkflowEngineConfig } from './process/workflow-engine.js';

// CLI Commands
import { speckitCommand, registerSpecKitCommands } from './cli-commands.js';

// =============================================================================
// RE-EXPORTS
// =============================================================================

// Memory Bridge
export {
  SpecKitMemoryBridge,
  type SpecKitConfig,
  type ParsedSpecification,
  type ParsedPlan,
  type ParsedTask,
  type ParsedUserStory,
  type ArtifactLineageEntry,
} from './memory-bridge.js';

// Version Tracker
export {
  SpecVersionTracker,
  type VersionInfo,
  type VersionDiff,
  type CascadeResult,
  type SpecSnapshot,
} from './version-tracker.js';

// =============================================================================
// PHASE 6: TEAM PROCESS & INTEGRATION LAYER
// =============================================================================

// Status Dashboard
export {
  StatusDashboard,
  type OutputFormat,
  type SpecStatus,
  type PlanStatus as DashboardPlanStatus,
  type TaskStatus as DashboardTaskStatus,
  type AgentActivity,
  type SystemOverview,
  type DashboardConfig,
} from './dashboard/status-dashboard.js';

// Audit Trail
export {
  AuditTrail,
  type ActionType,
  type AuditSeverity,
  type AuditEntry,
  type AuditQuery,
  type TimelineEntry,
  type AuditExportOptions,
  type AuditConfig,
} from './audit/audit-trail.js';

// Process Gates
export {
  ProcessGates,
  type GateId,
  type GateStatus,
  type GateRequirement,
  type GateDefinition,
  type GateCheckResult,
  type GateState,
  type GatesConfig,
} from './process/gates.js';

// Workflow Engine
export {
  WorkflowEngine,
  type WorkflowPhase,
  type WorkflowStatus,
  type WorkflowDefinition,
  type PhaseDefinition,
  type WorkflowSettings,
  type WorkflowInstance,
  type PhaseHistoryEntry,
  type WorkflowContext,
  type WorkflowTransition,
  type WorkflowEngineConfig,
} from './process/workflow-engine.js';

// CLI Commands
export { speckitCommand, registerSpecKitCommands } from './cli-commands.js';

// =============================================================================
// INTEGRATION FACTORY
// =============================================================================

/**
 * Configuration for the SpecKit integration
 */
export interface SpecKitIntegrationConfig {
  /** Path to the SQLite database file */
  dbPath: string;
  /** Directory where specs are stored */
  specsDirectory?: string;
  /** Automatically track artifact lineage */
  autoTrackLineage?: boolean;
}

/**
 * Combined SpecKit integration instance
 */
export interface SpecKitIntegration {
  bridge: SpecKitMemoryBridge;
  versionTracker: SpecVersionTracker;
  shutdown: () => Promise<void>;
}

/**
 * Create a complete SpecKit integration with all components initialized
 *
 * @param config - Configuration options
 * @param logger - Logger instance
 * @returns Initialized SpecKit integration
 *
 * @example
 * ```typescript
 * const integration = await createSpecKitIntegration({
 *   dbPath: './.speckit/speckit.db',
 *   specsDirectory: './specs',
 * }, logger);
 *
 * // Use the integration
 * await integration.bridge.onSpecGenerated('./specs/001/spec.md', 'agent');
 *
 * // Clean up
 * await integration.shutdown();
 * ```
 */
export async function createSpecKitIntegration(
  config: SpecKitIntegrationConfig,
  logger: ILogger
): Promise<SpecKitIntegration> {
  const bridge = new SpecKitMemoryBridge(
    {
      dbPath: config.dbPath,
      specsDirectory: config.specsDirectory,
      autoTrackLineage: config.autoTrackLineage ?? true,
    },
    logger
  );

  const versionTracker = new SpecVersionTracker(config.dbPath, logger);

  // Initialize both components
  await bridge.initialize();
  await versionTracker.initialize();

  return {
    bridge,
    versionTracker,
    shutdown: async () => {
      await bridge.shutdown();
      await versionTracker.shutdown();
    },
  };
}

// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

/**
 * Helper to determine the default database path
 */
export function getDefaultDbPath(projectRoot?: string): string {
  const root = projectRoot || process.cwd();
  return `${root}/.speckit/speckit.db`;
}

/**
 * Helper to determine the specs directory path
 */
export function getSpecsDirectory(projectRoot?: string): string {
  const root = projectRoot || process.cwd();
  return `${root}/specs`;
}

/**
 * Parse a feature branch name to extract the feature number and name
 *
 * @param branchName - Branch name like "001-my-feature"
 * @returns Parsed feature number and name
 */
export function parseFeatureBranch(branchName: string): {
  featureNumber: string;
  featureName: string;
} {
  const match = branchName.match(/^(\d+)-(.+)$/);
  if (match) {
    return {
      featureNumber: match[1],
      featureName: match[2].replace(/-/g, ' '),
    };
  }
  return {
    featureNumber: '000',
    featureName: branchName,
  };
}

/**
 * Generate a spec ID from a feature branch name
 *
 * @param featureBranch - Branch name
 * @returns Normalized spec ID
 */
export function generateSpecId(featureBranch: string): string {
  return `spec_${featureBranch.replace(/[^a-z0-9]/gi, '_').toLowerCase()}`;
}

/**
 * Generate a plan ID from a spec ID
 *
 * @param specId - Specification ID
 * @returns Plan ID
 */
export function generatePlanId(specId: string): string {
  return specId.replace(/^spec_/, 'plan_');
}

/**
 * Generate a task ID with proper formatting
 *
 * @param taskNumber - Task number (1, 2, 3, etc.)
 * @returns Formatted task ID (T001, T002, etc.)
 */
export function generateTaskId(taskNumber: number): string {
  return `T${taskNumber.toString().padStart(3, '0')}`;
}

// =============================================================================
// TYPES FOR EXTERNAL USE
// =============================================================================

/**
 * Status values for specifications
 */
export type SpecificationStatus = 'draft' | 'review' | 'approved' | 'implemented' | 'deprecated';

/**
 * Status values for implementation plans
 */
export type PlanStatus = 'draft' | 'review' | 'approved' | 'in_progress' | 'completed';

/**
 * Status values for tasks
 */
export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'blocked' | 'skipped';

/**
 * Types of artifacts that can be tracked
 */
export type ArtifactType =
  | 'specification'
  | 'plan'
  | 'task'
  | 'data_model'
  | 'contract'
  | 'test'
  | 'implementation'
  | 'research'
  | 'quickstart';

/**
 * Constitutional gate names
 */
export type ConstitutionalGate =
  | 'simplicity_gate'
  | 'anti_abstraction_gate'
  | 'integration_gate'
  | 'library_first'
  | 'cli_interface'
  | 'test_first';

/**
 * Constitutional compliance status
 */
export type ComplianceStatus = 'passed' | 'failed' | 'exception_granted';

/**
 * Validation status for artifacts
 */
export type ValidationStatus = 'pending' | 'valid' | 'invalid' | 'stale';

/**
 * Version change type
 */
export type VersionChangeType = 'major' | 'minor' | 'patch';

// =============================================================================
// PHASE 6: FULL INTEGRATION FACTORY
// =============================================================================

/**
 * Configuration for the full Phase 6 integration
 */
export interface FullIntegrationConfig {
  // Base config
  dbPath?: string;
  specsDirectory?: string;
  autoTrackLineage?: boolean;

  // Phase 6 config
  dashboard?: Partial<DashboardConfig>;
  audit?: Partial<AuditConfig>;
  gates?: Partial<GatesConfig>;
  workflow?: Partial<WorkflowEngineConfig>;

  // Integration options
  autoInitialize?: boolean;
}

/**
 * Full integration instance combining all SpecKit components
 */
export interface FullIntegrationInstance {
  // Core components
  bridge?: SpecKitMemoryBridge;
  versionTracker?: SpecVersionTracker;

  // Phase 6 components
  dashboard: StatusDashboard;
  audit: AuditTrail;
  gates: ProcessGates;
  workflow: WorkflowEngine;

  // Lifecycle
  initialize: () => Promise<void>;
  shutdown: () => Promise<void>;
  getStatus: () => Record<string, any>;
}

/**
 * Create a full SpecKit integration with all Phase 6 components
 *
 * @param config - Configuration options
 * @param logger - Optional logger instance
 * @returns Full integration instance
 *
 * @example
 * ```typescript
 * import { createFullIntegration } from './integrations/speckit';
 *
 * const integration = await createFullIntegration({
 *   dbPath: './.speckit/speckit.db',
 *   specsDirectory: './specs',
 *   autoInitialize: true,
 * });
 *
 * // Start a workflow
 * const workflow = await integration.workflow.startWorkflow('default-speckit-workflow');
 *
 * // Check gates
 * const gateResult = await integration.gates.checkGate('SPEC_APPROVED');
 *
 * // View dashboard
 * console.log(integration.dashboard.render('table'));
 *
 * // Query audit trail
 * const auditEntries = integration.audit.query({ action: 'spec_approved' });
 *
 * // Shutdown
 * await integration.shutdown();
 * ```
 */
export async function createFullIntegration(
  config: FullIntegrationConfig = {},
  logger?: ILogger
): Promise<FullIntegrationInstance> {
  // Create Phase 6 components
  const dashboard = new StatusDashboard(config.dashboard);
  const audit = new AuditTrail(config.audit);
  const gates = new ProcessGates(config.gates);
  const workflow = new WorkflowEngine(config.workflow);

  // Create bridge and version tracker if dbPath and logger provided
  let bridge: SpecKitMemoryBridge | undefined;
  let versionTracker: SpecVersionTracker | undefined;

  if (config.dbPath && logger) {
    bridge = new SpecKitMemoryBridge(
      {
        dbPath: config.dbPath,
        specsDirectory: config.specsDirectory,
        autoTrackLineage: config.autoTrackLineage ?? true,
      },
      logger
    );
    versionTracker = new SpecVersionTracker(config.dbPath, logger);
  }

  const instance: FullIntegrationInstance = {
    bridge,
    versionTracker,
    dashboard,
    audit,
    gates,
    workflow,

    initialize: async () => {
      // Initialize core components
      if (bridge) await bridge.initialize();
      if (versionTracker) await versionTracker.initialize();

      // Initialize Phase 6 components
      await dashboard.initialize();
      await audit.initialize();
      await gates.initialize();
      await workflow.initialize({
        gates,
        audit,
        dashboard,
      });

      // Record initialization in audit
      audit.record({
        action: 'system_event',
        severity: 'info',
        description: 'Full SpecKit integration initialized',
        initiatedBy: 'system',
        success: true,
      });
    },

    shutdown: async () => {
      // Record shutdown in audit
      audit.record({
        action: 'system_event',
        severity: 'info',
        description: 'Full SpecKit integration shutting down',
        initiatedBy: 'system',
        success: true,
      });

      // Shutdown in reverse order
      await workflow.shutdown();
      await gates.shutdown();
      await dashboard.shutdown();
      await audit.shutdown();

      if (versionTracker) await versionTracker.shutdown();
      if (bridge) await bridge.shutdown();
    },

    getStatus: () => ({
      initialized: true,
      components: {
        bridge: bridge ? 'ready' : 'disabled',
        versionTracker: versionTracker ? 'ready' : 'disabled',
        dashboard: 'ready',
        audit: 'ready',
        gates: 'ready',
        workflow: 'ready',
      },
      stats: {
        pendingGates: gates.getPendingGates().length,
        runningWorkflows: workflow.getRunningInstances().length,
        auditEntries: audit.getStatistics().totalEntries,
      },
    }),
  };

  // Auto-initialize if configured
  if (config.autoInitialize) {
    await instance.initialize();
  }

  return instance;
}

// =============================================================================
// DEFAULT EXPORT
// =============================================================================

export default {
  // Memory Bridge
  SpecKitMemoryBridge,
  SpecVersionTracker,
  createSpecKitIntegration,

  // Phase 6: Team Process & Integration
  StatusDashboard,
  AuditTrail,
  ProcessGates,
  WorkflowEngine,
  createFullIntegration,

  // CLI Commands
  speckitCommand,
  registerSpecKitCommands,

  // Utilities
  getDefaultDbPath,
  getSpecsDirectory,
  parseFeatureBranch,
  generateSpecId,
  generatePlanId,
  generateTaskId,
};
