/**
 * SpecKit Integration Module for Claude-Flow - Phase 1: Foundation Layer
 *
 * This module provides integration between spec-kit's Specification-Driven Development (SDD)
 * workflow and Claude-Flow's memory and agent coordination systems.
 *
 * Phase 1 Components:
 * - SpecKitMemoryBridge: Parses markdown artifacts and stores them in SQLite
 * - SpecVersionTracker: Tracks specification versions and detects cascade changes
 * - Database Schema: SQLite schema for specifications, plans, tasks, and lineage
 *
 * Usage:
 * ```typescript
 * import { SpecKitMemoryBridge, SpecVersionTracker, createSpecKitIntegration } from './integrations/speckit';
 *
 * const integration = await createSpecKitIntegration({
 *   dbPath: './.speckit/speckit.db',
 *   specsDirectory: './specs',
 * }, logger);
 *
 * // When spec is generated by /speckit.specify
 * const { specId } = await integration.bridge.onSpecGenerated(
 *   './specs/001-feature/spec.md',
 *   'spec-agent'
 * );
 *
 * // When plan is generated by /speckit.plan
 * const { planId } = await integration.bridge.onPlanGenerated(
 *   './specs/001-feature/plan.md',
 *   specId,
 *   'plan-agent',
 *   {
 *     researchPath: './specs/001-feature/research.md',
 *     dataModelPath: './specs/001-feature/data-model.md',
 *     contractsDir: './specs/001-feature/contracts',
 *     quickstartPath: './specs/001-feature/quickstart.md',
 *   }
 * );
 *
 * // When tasks are generated by /speckit.tasks
 * const { taskIds } = await integration.bridge.onTasksGenerated(
 *   './specs/001-feature/tasks.md',
 *   planId,
 *   'task-agent'
 * );
 *
 * // Track version changes and detect cascade
 * const cascadeResult = await integration.versionTracker.detectCascade(specId);
 * ```
 *
 * @module integrations/speckit
 */
import type { ILogger } from '../../core/logger.js';
import { SpecKitMemoryBridge } from './memory-bridge.js';
import { SpecVersionTracker } from './version-tracker.js';
import { StatusDashboard, type DashboardConfig } from './dashboard/status-dashboard.js';
import { AuditTrail, type AuditConfig } from './audit/audit-trail.js';
import { ProcessGates, type GatesConfig } from './process/gates.js';
import { WorkflowEngine, type WorkflowEngineConfig } from './process/workflow-engine.js';
import { registerSpecKitCommands } from './cli-commands.js';
export { SpecKitMemoryBridge, type SpecKitConfig, type ParsedSpecification, type ParsedPlan, type ParsedTask, type ParsedUserStory, type ArtifactLineageEntry, } from './memory-bridge.js';
export { SpecVersionTracker, type VersionInfo, type VersionDiff, type CascadeResult, type SpecSnapshot, } from './version-tracker.js';
export { StatusDashboard, type OutputFormat, type SpecStatus, type PlanStatus as DashboardPlanStatus, type TaskStatus as DashboardTaskStatus, type AgentActivity, type SystemOverview, type DashboardConfig, } from './dashboard/status-dashboard.js';
export { AuditTrail, type ActionType, type AuditSeverity, type AuditEntry, type AuditQuery, type TimelineEntry, type AuditExportOptions, type AuditConfig, } from './audit/audit-trail.js';
export { ProcessGates, type GateId, type GateStatus, type GateRequirement, type GateDefinition, type GateCheckResult, type GateState, type GatesConfig, } from './process/gates.js';
export { WorkflowEngine, type WorkflowPhase, type WorkflowStatus, type WorkflowDefinition, type PhaseDefinition, type WorkflowSettings, type WorkflowInstance, type PhaseHistoryEntry, type WorkflowContext, type WorkflowTransition, type WorkflowEngineConfig, } from './process/workflow-engine.js';
export { speckitCommand, registerSpecKitCommands } from './cli-commands.js';
/**
 * Configuration for the SpecKit integration
 */
export interface SpecKitIntegrationConfig {
    /** Path to the SQLite database file */
    dbPath: string;
    /** Directory where specs are stored */
    specsDirectory?: string;
    /** Automatically track artifact lineage */
    autoTrackLineage?: boolean;
}
/**
 * Combined SpecKit integration instance
 */
export interface SpecKitIntegration {
    bridge: SpecKitMemoryBridge;
    versionTracker: SpecVersionTracker;
    shutdown: () => Promise<void>;
}
/**
 * Create a complete SpecKit integration with all components initialized
 *
 * @param config - Configuration options
 * @param logger - Logger instance
 * @returns Initialized SpecKit integration
 *
 * @example
 * ```typescript
 * const integration = await createSpecKitIntegration({
 *   dbPath: './.speckit/speckit.db',
 *   specsDirectory: './specs',
 * }, logger);
 *
 * // Use the integration
 * await integration.bridge.onSpecGenerated('./specs/001/spec.md', 'agent');
 *
 * // Clean up
 * await integration.shutdown();
 * ```
 */
export declare function createSpecKitIntegration(config: SpecKitIntegrationConfig, logger: ILogger): Promise<SpecKitIntegration>;
/**
 * Helper to determine the default database path
 */
export declare function getDefaultDbPath(projectRoot?: string): string;
/**
 * Helper to determine the specs directory path
 */
export declare function getSpecsDirectory(projectRoot?: string): string;
/**
 * Parse a feature branch name to extract the feature number and name
 *
 * @param branchName - Branch name like "001-my-feature"
 * @returns Parsed feature number and name
 */
export declare function parseFeatureBranch(branchName: string): {
    featureNumber: string;
    featureName: string;
};
/**
 * Generate a spec ID from a feature branch name
 *
 * @param featureBranch - Branch name
 * @returns Normalized spec ID
 */
export declare function generateSpecId(featureBranch: string): string;
/**
 * Generate a plan ID from a spec ID
 *
 * @param specId - Specification ID
 * @returns Plan ID
 */
export declare function generatePlanId(specId: string): string;
/**
 * Generate a task ID with proper formatting
 *
 * @param taskNumber - Task number (1, 2, 3, etc.)
 * @returns Formatted task ID (T001, T002, etc.)
 */
export declare function generateTaskId(taskNumber: number): string;
/**
 * Status values for specifications
 */
export type SpecificationStatus = 'draft' | 'review' | 'approved' | 'implemented' | 'deprecated';
/**
 * Status values for implementation plans
 */
export type PlanStatus = 'draft' | 'review' | 'approved' | 'in_progress' | 'completed';
/**
 * Status values for tasks
 */
export type TaskStatus = 'pending' | 'in_progress' | 'completed' | 'blocked' | 'skipped';
/**
 * Types of artifacts that can be tracked
 */
export type ArtifactType = 'specification' | 'plan' | 'task' | 'data_model' | 'contract' | 'test' | 'implementation' | 'research' | 'quickstart';
/**
 * Constitutional gate names
 */
export type ConstitutionalGate = 'simplicity_gate' | 'anti_abstraction_gate' | 'integration_gate' | 'library_first' | 'cli_interface' | 'test_first';
/**
 * Constitutional compliance status
 */
export type ComplianceStatus = 'passed' | 'failed' | 'exception_granted';
/**
 * Validation status for artifacts
 */
export type ValidationStatus = 'pending' | 'valid' | 'invalid' | 'stale';
/**
 * Version change type
 */
export type VersionChangeType = 'major' | 'minor' | 'patch';
/**
 * Configuration for the full Phase 6 integration
 */
export interface FullIntegrationConfig {
    dbPath?: string;
    specsDirectory?: string;
    autoTrackLineage?: boolean;
    dashboard?: Partial<DashboardConfig>;
    audit?: Partial<AuditConfig>;
    gates?: Partial<GatesConfig>;
    workflow?: Partial<WorkflowEngineConfig>;
    autoInitialize?: boolean;
}
/**
 * Full integration instance combining all SpecKit components
 */
export interface FullIntegrationInstance {
    bridge?: SpecKitMemoryBridge;
    versionTracker?: SpecVersionTracker;
    dashboard: StatusDashboard;
    audit: AuditTrail;
    gates: ProcessGates;
    workflow: WorkflowEngine;
    initialize: () => Promise<void>;
    shutdown: () => Promise<void>;
    getStatus: () => Record<string, any>;
}
/**
 * Create a full SpecKit integration with all Phase 6 components
 *
 * @param config - Configuration options
 * @param logger - Optional logger instance
 * @returns Full integration instance
 *
 * @example
 * ```typescript
 * import { createFullIntegration } from './integrations/speckit';
 *
 * const integration = await createFullIntegration({
 *   dbPath: './.speckit/speckit.db',
 *   specsDirectory: './specs',
 *   autoInitialize: true,
 * });
 *
 * // Start a workflow
 * const workflow = await integration.workflow.startWorkflow('default-speckit-workflow');
 *
 * // Check gates
 * const gateResult = await integration.gates.checkGate('SPEC_APPROVED');
 *
 * // View dashboard
 * console.log(integration.dashboard.render('table'));
 *
 * // Query audit trail
 * const auditEntries = integration.audit.query({ action: 'spec_approved' });
 *
 * // Shutdown
 * await integration.shutdown();
 * ```
 */
export declare function createFullIntegration(config?: FullIntegrationConfig, logger?: ILogger): Promise<FullIntegrationInstance>;
declare const _default: {
    SpecKitMemoryBridge: typeof SpecKitMemoryBridge;
    SpecVersionTracker: typeof SpecVersionTracker;
    createSpecKitIntegration: typeof createSpecKitIntegration;
    StatusDashboard: typeof StatusDashboard;
    AuditTrail: typeof AuditTrail;
    ProcessGates: typeof ProcessGates;
    WorkflowEngine: typeof WorkflowEngine;
    createFullIntegration: typeof createFullIntegration;
    speckitCommand: import("commander").Command;
    registerSpecKitCommands: typeof registerSpecKitCommands;
    getDefaultDbPath: typeof getDefaultDbPath;
    getSpecsDirectory: typeof getSpecsDirectory;
    parseFeatureBranch: typeof parseFeatureBranch;
    generateSpecId: typeof generateSpecId;
    generatePlanId: typeof generatePlanId;
    generateTaskId: typeof generateTaskId;
};
export default _default;
//# sourceMappingURL=index.d.ts.map