"use strict";
/**
 * SpecKit Integration Module for Claude-Flow - Phase 1: Foundation Layer
 *
 * This module provides integration between spec-kit's Specification-Driven Development (SDD)
 * workflow and Claude-Flow's memory and agent coordination systems.
 *
 * Phase 1 Components:
 * - SpecKitMemoryBridge: Parses markdown artifacts and stores them in SQLite
 * - SpecVersionTracker: Tracks specification versions and detects cascade changes
 * - Database Schema: SQLite schema for specifications, plans, tasks, and lineage
 *
 * Usage:
 * ```typescript
 * import { SpecKitMemoryBridge, SpecVersionTracker, createSpecKitIntegration } from './integrations/speckit';
 *
 * const integration = await createSpecKitIntegration({
 *   dbPath: './.speckit/speckit.db',
 *   specsDirectory: './specs',
 * }, logger);
 *
 * // When spec is generated by /speckit.specify
 * const { specId } = await integration.bridge.onSpecGenerated(
 *   './specs/001-feature/spec.md',
 *   'spec-agent'
 * );
 *
 * // When plan is generated by /speckit.plan
 * const { planId } = await integration.bridge.onPlanGenerated(
 *   './specs/001-feature/plan.md',
 *   specId,
 *   'plan-agent',
 *   {
 *     researchPath: './specs/001-feature/research.md',
 *     dataModelPath: './specs/001-feature/data-model.md',
 *     contractsDir: './specs/001-feature/contracts',
 *     quickstartPath: './specs/001-feature/quickstart.md',
 *   }
 * );
 *
 * // When tasks are generated by /speckit.tasks
 * const { taskIds } = await integration.bridge.onTasksGenerated(
 *   './specs/001-feature/tasks.md',
 *   planId,
 *   'task-agent'
 * );
 *
 * // Track version changes and detect cascade
 * const cascadeResult = await integration.versionTracker.detectCascade(specId);
 * ```
 *
 * @module integrations/speckit
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.registerSpecKitCommands = exports.speckitCommand = exports.WorkflowEngine = exports.ProcessGates = exports.AuditTrail = exports.StatusDashboard = exports.SpecVersionTracker = exports.SpecKitMemoryBridge = void 0;
exports.createSpecKitIntegration = createSpecKitIntegration;
exports.getDefaultDbPath = getDefaultDbPath;
exports.getSpecsDirectory = getSpecsDirectory;
exports.parseFeatureBranch = parseFeatureBranch;
exports.generateSpecId = generateSpecId;
exports.generatePlanId = generatePlanId;
exports.generateTaskId = generateTaskId;
exports.createFullIntegration = createFullIntegration;
const memory_bridge_js_1 = require("./memory-bridge.js");
const version_tracker_js_1 = require("./version-tracker.js");
// Phase 6: Team Process & Integration Layer
const status_dashboard_js_1 = require("./dashboard/status-dashboard.js");
const audit_trail_js_1 = require("./audit/audit-trail.js");
const gates_js_1 = require("./process/gates.js");
const workflow_engine_js_1 = require("./process/workflow-engine.js");
// CLI Commands
const cli_commands_js_1 = require("./cli-commands.js");
// =============================================================================
// RE-EXPORTS
// =============================================================================
// Memory Bridge
var memory_bridge_js_2 = require("./memory-bridge.js");
Object.defineProperty(exports, "SpecKitMemoryBridge", { enumerable: true, get: function () { return memory_bridge_js_2.SpecKitMemoryBridge; } });
// Version Tracker
var version_tracker_js_2 = require("./version-tracker.js");
Object.defineProperty(exports, "SpecVersionTracker", { enumerable: true, get: function () { return version_tracker_js_2.SpecVersionTracker; } });
// =============================================================================
// PHASE 6: TEAM PROCESS & INTEGRATION LAYER
// =============================================================================
// Status Dashboard
var status_dashboard_js_2 = require("./dashboard/status-dashboard.js");
Object.defineProperty(exports, "StatusDashboard", { enumerable: true, get: function () { return status_dashboard_js_2.StatusDashboard; } });
// Audit Trail
var audit_trail_js_2 = require("./audit/audit-trail.js");
Object.defineProperty(exports, "AuditTrail", { enumerable: true, get: function () { return audit_trail_js_2.AuditTrail; } });
// Process Gates
var gates_js_2 = require("./process/gates.js");
Object.defineProperty(exports, "ProcessGates", { enumerable: true, get: function () { return gates_js_2.ProcessGates; } });
// Workflow Engine
var workflow_engine_js_2 = require("./process/workflow-engine.js");
Object.defineProperty(exports, "WorkflowEngine", { enumerable: true, get: function () { return workflow_engine_js_2.WorkflowEngine; } });
// CLI Commands
var cli_commands_js_2 = require("./cli-commands.js");
Object.defineProperty(exports, "speckitCommand", { enumerable: true, get: function () { return cli_commands_js_2.speckitCommand; } });
Object.defineProperty(exports, "registerSpecKitCommands", { enumerable: true, get: function () { return cli_commands_js_2.registerSpecKitCommands; } });
/**
 * Create a complete SpecKit integration with all components initialized
 *
 * @param config - Configuration options
 * @param logger - Logger instance
 * @returns Initialized SpecKit integration
 *
 * @example
 * ```typescript
 * const integration = await createSpecKitIntegration({
 *   dbPath: './.speckit/speckit.db',
 *   specsDirectory: './specs',
 * }, logger);
 *
 * // Use the integration
 * await integration.bridge.onSpecGenerated('./specs/001/spec.md', 'agent');
 *
 * // Clean up
 * await integration.shutdown();
 * ```
 */
async function createSpecKitIntegration(config, logger) {
    const bridge = new memory_bridge_js_1.SpecKitMemoryBridge({
        dbPath: config.dbPath,
        specsDirectory: config.specsDirectory,
        autoTrackLineage: config.autoTrackLineage ?? true,
    }, logger);
    const versionTracker = new version_tracker_js_1.SpecVersionTracker(config.dbPath, logger);
    // Initialize both components
    await bridge.initialize();
    await versionTracker.initialize();
    return {
        bridge,
        versionTracker,
        shutdown: async () => {
            await bridge.shutdown();
            await versionTracker.shutdown();
        },
    };
}
// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================
/**
 * Helper to determine the default database path
 */
function getDefaultDbPath(projectRoot) {
    const root = projectRoot || process.cwd();
    return `${root}/.speckit/speckit.db`;
}
/**
 * Helper to determine the specs directory path
 */
function getSpecsDirectory(projectRoot) {
    const root = projectRoot || process.cwd();
    return `${root}/specs`;
}
/**
 * Parse a feature branch name to extract the feature number and name
 *
 * @param branchName - Branch name like "001-my-feature"
 * @returns Parsed feature number and name
 */
function parseFeatureBranch(branchName) {
    const match = branchName.match(/^(\d+)-(.+)$/);
    if (match) {
        return {
            featureNumber: match[1],
            featureName: match[2].replace(/-/g, ' '),
        };
    }
    return {
        featureNumber: '000',
        featureName: branchName,
    };
}
/**
 * Generate a spec ID from a feature branch name
 *
 * @param featureBranch - Branch name
 * @returns Normalized spec ID
 */
function generateSpecId(featureBranch) {
    return `spec_${featureBranch.replace(/[^a-z0-9]/gi, '_').toLowerCase()}`;
}
/**
 * Generate a plan ID from a spec ID
 *
 * @param specId - Specification ID
 * @returns Plan ID
 */
function generatePlanId(specId) {
    return specId.replace(/^spec_/, 'plan_');
}
/**
 * Generate a task ID with proper formatting
 *
 * @param taskNumber - Task number (1, 2, 3, etc.)
 * @returns Formatted task ID (T001, T002, etc.)
 */
function generateTaskId(taskNumber) {
    return `T${taskNumber.toString().padStart(3, '0')}`;
}
/**
 * Create a full SpecKit integration with all Phase 6 components
 *
 * @param config - Configuration options
 * @param logger - Optional logger instance
 * @returns Full integration instance
 *
 * @example
 * ```typescript
 * import { createFullIntegration } from './integrations/speckit';
 *
 * const integration = await createFullIntegration({
 *   dbPath: './.speckit/speckit.db',
 *   specsDirectory: './specs',
 *   autoInitialize: true,
 * });
 *
 * // Start a workflow
 * const workflow = await integration.workflow.startWorkflow('default-speckit-workflow');
 *
 * // Check gates
 * const gateResult = await integration.gates.checkGate('SPEC_APPROVED');
 *
 * // View dashboard
 * console.log(integration.dashboard.render('table'));
 *
 * // Query audit trail
 * const auditEntries = integration.audit.query({ action: 'spec_approved' });
 *
 * // Shutdown
 * await integration.shutdown();
 * ```
 */
async function createFullIntegration(config = {}, logger) {
    // Create Phase 6 components
    const dashboard = new status_dashboard_js_1.StatusDashboard(config.dashboard);
    const audit = new audit_trail_js_1.AuditTrail(config.audit);
    const gates = new gates_js_1.ProcessGates(config.gates);
    const workflow = new workflow_engine_js_1.WorkflowEngine(config.workflow);
    // Create bridge and version tracker if dbPath and logger provided
    let bridge;
    let versionTracker;
    if (config.dbPath && logger) {
        bridge = new memory_bridge_js_1.SpecKitMemoryBridge({
            dbPath: config.dbPath,
            specsDirectory: config.specsDirectory,
            autoTrackLineage: config.autoTrackLineage ?? true,
        }, logger);
        versionTracker = new version_tracker_js_1.SpecVersionTracker(config.dbPath, logger);
    }
    const instance = {
        bridge,
        versionTracker,
        dashboard,
        audit,
        gates,
        workflow,
        initialize: async () => {
            // Initialize core components
            if (bridge)
                await bridge.initialize();
            if (versionTracker)
                await versionTracker.initialize();
            // Initialize Phase 6 components
            await dashboard.initialize();
            await audit.initialize();
            await gates.initialize();
            await workflow.initialize({
                gates,
                audit,
                dashboard,
            });
            // Record initialization in audit
            audit.record({
                action: 'system_event',
                severity: 'info',
                description: 'Full SpecKit integration initialized',
                initiatedBy: 'system',
                success: true,
            });
        },
        shutdown: async () => {
            // Record shutdown in audit
            audit.record({
                action: 'system_event',
                severity: 'info',
                description: 'Full SpecKit integration shutting down',
                initiatedBy: 'system',
                success: true,
            });
            // Shutdown in reverse order
            await workflow.shutdown();
            await gates.shutdown();
            await dashboard.shutdown();
            await audit.shutdown();
            if (versionTracker)
                await versionTracker.shutdown();
            if (bridge)
                await bridge.shutdown();
        },
        getStatus: () => ({
            initialized: true,
            components: {
                bridge: bridge ? 'ready' : 'disabled',
                versionTracker: versionTracker ? 'ready' : 'disabled',
                dashboard: 'ready',
                audit: 'ready',
                gates: 'ready',
                workflow: 'ready',
            },
            stats: {
                pendingGates: gates.getPendingGates().length,
                runningWorkflows: workflow.getRunningInstances().length,
                auditEntries: audit.getStatistics().totalEntries,
            },
        }),
    };
    // Auto-initialize if configured
    if (config.autoInitialize) {
        await instance.initialize();
    }
    return instance;
}
// =============================================================================
// DEFAULT EXPORT
// =============================================================================
exports.default = {
    // Memory Bridge
    SpecKitMemoryBridge: memory_bridge_js_1.SpecKitMemoryBridge,
    SpecVersionTracker: version_tracker_js_1.SpecVersionTracker,
    createSpecKitIntegration,
    // Phase 6: Team Process & Integration
    StatusDashboard: status_dashboard_js_1.StatusDashboard,
    AuditTrail: audit_trail_js_1.AuditTrail,
    ProcessGates: gates_js_1.ProcessGates,
    WorkflowEngine: workflow_engine_js_1.WorkflowEngine,
    createFullIntegration,
    // CLI Commands
    speckitCommand: cli_commands_js_1.speckitCommand,
    registerSpecKitCommands: cli_commands_js_1.registerSpecKitCommands,
    // Utilities
    getDefaultDbPath,
    getSpecsDirectory,
    parseFeatureBranch,
    generateSpecId,
    generatePlanId,
    generateTaskId,
};
//# sourceMappingURL=index.js.map